name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: install deps
      run: sudo apt install build-essential cmake flex bison clang lld git
    - name: make
      working-directory: ./plugin
      run: make
