name: Github CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: install deps
      run: sudo apt-get update -y && sudo apt-get install -y flex bison clang lld
    - name: make
      working-directory: ./plugin
      run: |
        export PATH=$PATH:/usr/lib/llvm-6.0/bin
        make
